### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by philomory** [jtopjian/go-jerakia#6]
I can't help but notice that the software in this repository has no assigned open source license that I can tell (nothing in the README, no LICENSE file, etc). Other software from the Jerakia organization (such as jerakia/jerakia) is under the Apache 2.0 license. Is the intent that this package is licensed the same way, or did you have something else in mind?

**Comment by philomory** [comment]
@jtopjian Tagging you here as well; you're the committer for all but one commit in this repository, so you seem like the best person to ask in this case as well.

**Comment by jtopjian** [comment]
@philomory I've added a license to this repository as well.

**Comment by philomory** [comment]
Thanks a bunch!
